//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.29 at 12:22:15 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springapitest.com/spring-boo-soap-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soap.two.soapAPI.generatedPackages.com.springapitest.spring_boo_soap_example;
